baseURL = "https://pabloos.github.io/"
languageCode = "en-us"
title = "byBit"
theme = "hyde"

[Menus]
main = [
    {Name = "github", URL = "https://www.github.com/pabloos"},
    {Name = "linkedin", URL = "https://www.linkedin.com/in/pablocdiaz"},
    {Name = "twitter", URL = "https://www.twitter.com/PabloCDaz"},
    {Name = "stackoverflow", URL = "https://stackoverflow.com/users/5510296/pablo-cumpi%c3%a1n-d%c3%adaz"},
    # {Name = "email", URL = "pablocumpia@gmail.com"},
    {name = "golang", URL = "/golang/"}
]

[params]
    layoutReverse = false
    themeColor = "theme-base-0f"

    description = "golang, docker and much more"
    highlightjs = true
    authorimage = "gopher.png"
    highlightjsstyle = "zenburn"
    highlightjslanguages = ["go"]
    postNavigation = true

# [params.social]
#     github = "pabloos"
#     linkedin = "pablocdiaz"
#     twitter = "PabloCDaz"
#     stackoverflow = "5510296/pablo-cumpián-díaz"
#     email = "pablocumpia@gmail.com"

# [[menu.main]]
#     name = "golang"
#     identifier = "go"
#     url = "/golang/"
#     weight = "1"
