baseURL = "https://pabloos.github.io/"
languageCode = "en-us"
title = "by bit"
theme = "hyde"
googleAnalytics = "UA-163718289-1"

[Menus]
main = [
    {name = "concurrency", URL = "/concurrency/", weight = 1},
    {name = "testing", URL= "/testing/", weight = 2},
    {name = "languages", URL="/languages/", weight = 3},
    {Name = "github", URL = "https://www.github.com/pabloos", weight = 10},
    {Name = "linkedin", URL = "https://www.linkedin.com/in/pablocdiaz", weight = 9},
    {Name = "twitter", URL = "https://www.twitter.com/PabloCDaz"},
    # {Name = "stackoverflow", URL = "https://stackoverflow.com/users/5510296/pablo-cumpi%c3%a1n-d%c3%adaz"},
    {Name = "email", URL = "mailto:pablocumpia@gmail.com"},
]

[params]
    layoutReverse = false
    themeColor = "theme-base-0f"

    description = "Pablo Cumpian, on software"
    highlightjs = true
    authorimage = "gopher.png"
    highlightjsstyle = "zenburn"
    highlightjslanguages = ["go"]
    postNavigation = true